# Generated by Django 5.2.6 on 2025-09-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude'], name='myapp_pin_latitud_8ea149_idx'), models.Index(fields=['longitude'], name='myapp_pin_longitu_d2347d_idx'), models.Index(fields=['latitude', 'longitude'], name='myapp_pin_latitud_7b70f3_idx'), models.Index(fields=['is_active'], name='myapp_pin_is_acti_740362_idx')],
            },
        ),
    ]
