# Generated by Django 5.2.6 on 2025-10-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='link',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='platform',
        ),
        migrations.CreateModel(
            name='YouTubePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_pin', to='myapp.pin')),
            ],
        ),
    ]
