# Generated by Django 5.2.6 on 2025-09-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['latitude'], name='myapp_pin_latitud_8ea149_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['longitude'], name='myapp_pin_longitu_d2347d_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['latitude', 'longitude'], name='myapp_pin_latitud_7b70f3_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['is_active'], name='myapp_pin_is_acti_740362_idx'),
        ),
    ]
