# Generated by Django 5.2.6 on 2025-09-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pin_myapp_pin_latitud_8ea149_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='title',
        ),
    ]
