# Generated by Django 5.2.6 on 2025-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
