# Generated by Django 5.2.6 on 2025-10-04 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_pin_link_remove_pin_platform_youtubepin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('video_id', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_pin', to='myapp.pin')),
            ],
        ),
    ]
