# Generated by Django 5.2.6 on 2025-09-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_link_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
