# Generated by Django 5.2.6 on 2025-10-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tiktokpin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokpin',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='tiktokpin',
            name='author_url',
        ),
        migrations.RemoveField(
            model_name='tiktokpin',
            name='html',
        ),
        migrations.RemoveField(
            model_name='tiktokpin',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='tiktokpin',
            name='title',
        ),
    ]
