# Generated by Django 5.2.6 on 2025-10-10 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_tiktokpin_author_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortcode', models.CharField(max_length=255)),
                ('pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_pin', to='myapp.pin')),
            ],
        ),
    ]
