# Generated by Django 5.2.6 on 2025-10-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_instagrampin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post_id', models.CharField(max_length=50)),
                ('pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reddit_pin', to='myapp.pin')),
            ],
        ),
    ]
